### PR TITLE
Support layer masking

### PR DESCRIPTION
**Pull request by warent**
image
image
image

### CODE REVIEW

**Comment by mharitsnf** [comment]
Thanks for the contribution! Tried the masking and it works great. But I discovered a bug that allows you to open multiple windows. I can operate on any of those windows, but confirming the change will only close the last opened one and the rest still stays. Would you mind addressing those?

https://github.com/user-attachments/assets/11109db5-a0f8-4211-b928-22d8919c3f41

**Comment by warent** [comment]
Haha oops good catch. What do you suggest the menu button should do in the case of a window already being open? We could close the existing window, or perhaps bring it to focus, or maybe we disable the menu button entirely

**Comment by mharitsnf** [comment]
Hmm, not totally sure, but was thinking maybe bring it to focus? I thought it would be the most familiar for people since Windows or maybe other OSs do something like that as well 😅 what do you think?

**Comment by oparisy** [comment]
I'd suggest taking inspiration from the Godot editor itself, since it's cross platform while OS behavior may vary with respect to child windows.

Are there examples in Godot of child windows popping up at the press of a button?

**Comment by warent** [comment]
> I'd suggest taking inspiration from the Godot editor itself, since it's cross platform while OS behavior may vary with respect to child windows.

This is really good thinking.

> Are there examples in Godot of child windows popping up at the press of a button?

So the only examples I can find actually block the entire Godot main window until the child window is closed. I guess we could do that? I think it's called "exclusive" so I'll just enable that.

**Comment by mharitsnf** [comment]
> I'd suggest taking inspiration from the Godot editor itself, since it's cross platform while OS behavior may vary with respect to child windows.

Thanks for the suggestion, very helpful.

I think everything looks good, I'm merging this. Thanks for the contribution again!

**Pull request merged**
